spring:
  datasource: 
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec-202004d
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: ec202004d@gmail.com
    password: kszdbwjalihjifed
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
